### PR TITLE
adding support for the $in operator on a list contains regex objects

### LINKED ISSUE #334: Cannot handle {"$in": [re.compile("...")]}
In MongoDB ([docs](https://docs.mongodb.com/manual/reference/operator/query/regex/)), this following query should work:

`{"$in": [re.compile("...")]}`

However in mongomock this doesn't work, as the "$in" operator just runs the python `in` operator on the given list.

### PR DESCRIPTION
**Pull request by tzachyrm**
Fix #334

### CODE REVIEW

**Comment by boxmansf** [comment]
@mdomke @vmalloc - could you please approve and merge this PR ?
Thanks !

**Comment by baruchoxman** [comment]
@vmalloc @mdomke Any chance to approve and merge this PR ?
Otherwise - me and @tzachyrm would be happy to take more ownership in this project (as we saw you're looking for maintainers), as we are heavily dependent on it in our work, so if possible - we'd like getting the permissions to approve and merge PRs.

**Comment by boxmansf** [comment]
@vmalloc, looks like you've recently reviewed some other PRs, could you please review this one as well ?

**Comment by vmalloc** [comment]
Yeah, sorry - still going through the backlog. This looks ok though - so merging it.

**Pull request merged**
