### PR TITLE
Implement a basic version of write_concern property.

### LINKED ISSUE #406: mongomock not working with mongoengine
Code to reproduce this problem:

```python
from mongoengine import connect, Document, fields

connect('mongoenginetest', host='mongomock://localhost')

class User(Document):
    _id = fields.IntField(primary_key=True)
    name = fields.StringField()

user = User(_id=1, name="Alice")

User.objects.insert(user) # TypeError: 'Collection' object is not callable
```

Looks like it is because mongomock doesn't implement ``write_concerns`` at all. and it calls ``collection.write_concern.document`` while doing insert.

And ``collection.write_concern`` doesn't return a ``WriteConcern`` object, it just returns another collection.

And I think this could solve the problem:

```python
class Collection(...):
    ...
    def __init__(...):
        self.__write_concerns = WriteConcern()

    @property
    def write_concerns(self):
        return self.__write_concerns

# and in write_concerns.py, we can do
class WriteConcern(object):
    __slots__ = ("__document", "__acknowledged", "__server_default")

    def __init__(self, w=None, wtimeout=None, j=None, fsync=None):
        self.__document = {}

    @property
    def document(self):
        return self.__document.copy()

```

Hope my suggestion helps

### PR DESCRIPTION
**Pull request by pcorpet**
Fixes #406.

### CODE REVIEW

**Comment by Motor-taxi-master-rider** [comment]
I think this commit will solve the problem that: Using mongomock in mongoengine, `update` function will not work well. It is great to have this.

**Comment by zozoens31** [comment]
Please, add a test that WriteConcern() object is immutable (see http://api.mongodb.com/python/current/api/pymongo/write_concern.html#pymongo.write_concern.WriteConcern.document)

**Comment by pcorpet** [comment]
@zozoens31 Done.

**Comment by zozoens31** [comment]
LGTM

**Comment by vmalloc** [comment]
A long shot - but are @zozoens31 and @pcorpet related?

**Comment by pcorpet** [comment]
Not that long :-)
https://www.bayesimpact.org/about
http://fcorpet.free.fr/indexan.html

**Comment by vmalloc** [comment]
Oh I see LOL

**Pull request merged**
