### PR TITLE
add support for mergeObjects operator

### PR DESCRIPTION
**Pull request by elbehery95**
As per https://github.com/mongomock/mongomock/issues/642

The current implementation follows the operator as defined such that on all null an empty doc is returned, and the docs are merged using ``dict.update`` method

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
Thanks for your PR.

Please add multiple tests in test__mongomock to ensure there are no regressions in the future.

**Comment by elbehery95** [comment]
removed mergeobjects exception checking tests and added a single test__merge_objects under the aggregate tests

**Comment by pcorpet** [comment]
Thanks, almost there. Please fix the remaining styling issues
https://travis-ci.org/github/mongomock/mongomock/jobs/754673610

**Comment by pcorpet** [comment]
Thanks @elbehery95 for the hard work!

**Pull request merged**
