### PR TITLE
Allow mongomock as database for gridfs

### PR DESCRIPTION
**Pull request by c0d3d**
… of the mongomock client. Most of the code is copied from pymongo's gridfs module

### CODE REVIEW

**Comment by srinivasreddy** [comment]
This is too big. I need a week.

**Comment by c0d3d** [comment]
No worries, it is a big feature.

**Comment by touilleMan** [comment]
Hi,

I've end up with a simpler solution : the idea is to monkey patch the `isinstance` function for the `gridfs` module. This way `gridfs` consider `mongomock.Collection` and `mongomock.Database` to be regular class along with `pymongo.Collection` and `pymongo.Database`.

I'm wondering if this monkeypatch should be applied automatically when importing mongomock or only provided (hence the user should explicitly call it when he wants mongomock support for gridfs)

Here is the code:

```python
def monkeypatch_pymongo_gridfs_for_mongomock():
    """
    Gridfs library use `isinstance` to make sure the passed elements
    are valid `pymongo.Database/Collection`. Hence we have to monkeypatch
    isinstance beahviour to also accept `mongomock.Database/Collection`.
    Note we only patch isinstance within the gridfs module, especially because
    overloading this builtins makes the code really slow.
    """

    import builtins
    from importlib import import_module
    from pymongo.collection import Collection as PyMongoCollection
    from pymongo.database import Database as PyMongoDatabase
    from mongomock import Database as MongoMockDatabase, Collection as MongoMockCollection

    def isinstance_patched(object, classinfo):
        if type(classinfo) is tuple:
            classesinfo = list(classinfo)
        else:
            classesinfo = [classinfo]
        mocked_needed = []
        for cls in classesinfo:
            if cls is PyMongoCollection:
                mocked_needed.append(MongoMockCollection)
            if cls is PyMongoDatabase:
                mocked_needed.append(MongoMockDatabase)
        return builtins.isinstance(object, tuple(classesinfo + mocked_needed))

    for modname in ('gridfs', 'gridfs.grid_file', 'gridfs.errors'):
        mod = import_module(modname)
        mod.__builtins__ = mod.__builtins__.copy()
        mod.__builtins__['isinstance'] = isinstance_patched
```

**Comment by c0d3d** [comment]
I like your solution much better. I'll swap it out. 

I like the idea of an explicit call to enable it better than auto-patching; allows for more flexibility.

**Comment by c0d3d** [comment]
@srinivasreddy @touilleMan What are your thoughts now?

**Comment by fabian-marquardt** [comment]
@srinivasreddy @touilleMan Are there chances that this will be merged anytime soon? Missing GridFS support is currently the only thing missing before I can really start to use mongomock for unit tests within my projects.

**Comment by srinivasreddy** [comment]
Sorry for the late reply @c0d3d. @fabian-marquardt I am no longer associated with this project. Please direct all of your questions and PRs to @vmalloc  @mdomke  .

Thanks a lot for your patience.

**Comment by c0d3d** [comment]
@vmalloc @mdomke Any thoughts? Don't want this one falling through the cracks again :P

**Comment by fabian-marquardt** [comment]
@vmalloc @mdomke any chance you can merge this one?

**Comment by c0d3d** [comment]
@vmalloc @mdomke @fabian-marquardt I've rebased onto develop, so feel free to look this over :stuck_out_tongue:

**Comment by c0d3d** [comment]
@vmalloc @mdomke . Looks like this is still open. Can you please take a look. It is actually a pretty small code change.

**Comment by vmalloc** [comment]
@c0d3d it seems like this PR is lacking a test for the change introduced. It also appears to contain commits not really related to the change (including one from a different PR?)

Can you please rebase and add a test case for this change?

**Comment by c0d3d** [comment]
@vmalloc There are tests for the new code in `tests/test__gridfs.py`.

I'm not sure what you mean about the changes that are unrelated / from a different PR. When I wrote this I had to fix some stuff to allow my tests to work. I'll rebase later today.

**Comment by vmalloc** [comment]
@c0d3d oh sorry - missed that test file. In any case when I look at `commits` I see 5 different commits, with titles such as "Don't need these anymore" and "touilleMan's code from pull request". If possible - please format the change as a single coherent commit. 

Thanks and sorry for the hassle - I'll merge it today once you rebase.

**Comment by c0d3d** [comment]
No worries. The commit message about touilleMan's code was from their comment on this PR, lol. I could see how that would be misleading, so my apologies. When I do the rebase I'll squash into a single commit.

**Comment by c0d3d** [comment]
@vmalloc , All yours now.

**Comment by vmalloc** [comment]
Thanks for contributing!!!

**Comment by embray** [comment]
Hi, I need to test an application that uses `GridFS` and, as luck would have it, this was merged just 9 days ago, so thanks for that!

However, I've encountered two issues (so far) at least one of which I'm surprised passed testing.  First of all, although I still prefer to use Python 3, in production I'm still using Python 2.  I tested with Python 2 and was immediately blocked by

```
import builtins
```

If I install the [`future`](https://pypi.org/project/future/) module that works around it, and perhaps the test environment for mongomock happens to include that as well, so it worked.  I don't mind relying on something like this for Python 2 compatibility, but in that case `future` should be added as a runtime dependency of mongomock :|

The other issue I hit on immediately after that while testing this out was:

```
>>> gfs.put("Hello!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/gridfs/__init__.py", line 123, in put
    grid_file.close()
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/gridfs/grid_file.py", line 307, in close
    self.__flush()
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/gridfs/grid_file.py", line 285, in __flush
    self.__flush_buffer()
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/gridfs/grid_file.py", line 277, in __flush_buffer
    self.__flush_data(self._buffer.getvalue())
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/gridfs/grid_file.py", line 256, in __flush_data
    self.__ensure_indexes()
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/gridfs/grid_file.py", line 197, in __ensure_indexes
    self.__create_index(self._coll.files, _F_INDEX, False)
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/gridfs/grid_file.py", line 188, in __create_index
    collection.list_indexes(session=self._session)]
TypeError: list_indexes() got an unexpected keyword argument 'session'
```

this is with 

```
>>> pymongo.__version__
'3.6.1'
```

I'm not explicitly using sessions, but because mongomock's `Collection.list_indexes` doesn't accept the session argument I'm again dead in the water.  As mongomock doesn't support sessions yet (and I don't need it to) would it at least be acceptable to add the session argument to the appropriate APIs, and raise `NotImpementedError` if it's passed anything besides `None`?

**Comment by embray** [comment]
Hrm, downgraded to pymongo 3.5.1, and now `put()/get()` as well as `list()` worked, but not `find*()`.  E.g.:

```
>>> import mongomock
>>> import mongomock.gridfs
>>> import gridfs
>>> mongomock.gridfs.enable_gridfs_integration()
>>> fake_conn = mongomock.MongoClient()
>>> gfs = gridfs.GridFS(fake_conn['test_db'])
>>> fid = gfs.put("Hello world!", filename='hello.txt')
>>> gfs.list()
['hello.txt']
>>> gfs.get(fid).read()
'Hello world!'
>>> list(gfs.find())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/gridfs/grid_file.py", line 659, in next
    next_file = super(GridOutCursor, self).next()
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/pymongo/cursor.py", line 1132, in next
    if len(self.__data) or self._refresh():
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/pymongo/cursor.py", line 1055, in _refresh
    self.__collation))
  File "/home/embray/.virtualenvs/fancy-rat/lib/python2.7/site-packages/pymongo/cursor.py", line 892, in __send_message
    **kwargs)
TypeError: 'Database' object is not callable
```

I'm not sure what version of the `gridfs` package this was tested against (though the `tox.ini` contains `pymongo<3.6`).  But ISTM more mocking is required somewhere.  For more context to the last line of that traceback:

```
pymongo/cursor.pyc in __send_message(self, operation)
    890             try:
    891                 response = client._send_message_with_response(operation,
--> 892                                                               **kwargs)
    893                 self.__address = response.address
    894                 if self.__exhaust:
```

The fake client does not have a `_send_message_with_response` method, whatever that's suppose to do, so it returns a `Database` by that name.

**Comment by vmalloc** [comment]
@embray thanks for reporting. Just out of curiosity, does it work when you try it with Python 3? I'm trying to understand if it's a 2.x-only breakage or something bigger.

The GridFS support is, in my opinion, still a bit experimental since there don't seem to be a lot of users using it, and I'm assuming we haven't covered all bases when testing it as you mention. I'm very open to PRs improving this support and adding tests, so any help is more than welcome.

**Comment by embray** [comment]
I don't think it's a problem unique to Python 2.x, but I'll try it and see.

**Comment by LaundroMat** [comment]
Am I wrong in supposing that GridFS support is still unavailable? I'm getting this error

```
self = <gridfs.GridFS object at 0x10950590>
database = Database(mongomock.MongoClient('localhost', 27017), 'test')
collection = 'images', disable_md5 = False

    def __init__(self, database, collection="fs", disable_md5=False):
        """Create a new instance of :class:`GridFS`.
    
        Raises :class:`TypeError` if `database` is not an instance of
        :class:`~pymongo.database.Database`.
    
        :Parameters:
          - `database`: database to use
          - `collection` (optional): root collection to use
          - `disable_md5` (optional): When True, MD5 checksums will not be
            computed for uploaded files. Useful in environments where MD5
            cannot be used for regulatory or other reasons. Defaults to False.
    
        .. versionchanged:: 3.1
           Indexes are only ensured on the first write to the DB.
    
        .. versionchanged:: 3.0
           `database` must use an acknowledged
           :attr:`~pymongo.database.Database.write_concern`
    
        .. mongodoc:: gridfs
        """
        if not isinstance(database, Database):
>           raise TypeError("database must be an instance of Database")
E           TypeError: database must be an instance of Database

C:\----\----\.virtualenvs\-----\lib\site-packages\gridfs\__init__.py:62: TypeError

```

I'm using the latest development version (3.15.1.dev1).

**Pull request merged**
