### PR TITLE
Enable pymongo bulk_write

### PR DESCRIPTION
**Pull request by afouchet**
Mongomock did not have the proper behavior when using 

collection.bulk_write(operations)

which allows to make several operations in one call. The operations are (InsertOne, DeleteOne, DeleteMany, ReplaceOne, UpdateOne, UpdateMany), in pymongo.

In this PR, the bulk_write behavior + the tests for each operation.

Here is a gist with the usage of bulk_write:
https://gist.github.com/afouchet/6af2fe7e1010a7197e8e545549f45464

### CODE REVIEW

**Comment by afouchet** [comment]
Hi @srinivasreddy! Any comment or feedback on this?

**Comment by srinivasreddy** [comment]
Thanks!!

**Comment by afouchet** [comment]
my pleasure

**Comment by edengreen** [comment]
Thanks for the great work (looking forward to see it officially in pypi).
One small issue - could you please add support for pymongo's BulkWriteResult?
Should be something like replacing (in mongomock.collection.BulkOperationBuilder.execute):
`return result`
with
`return BulkWriteResult(result, True)`

Thanks!

**Comment by srinivasreddy** [comment]
@edengreen  Are you interested in making a PR for that change?

**Comment by srinivasreddy** [comment]
@edengreen  Also, it is very difficult to track these requests in comments. Could you please raise this as an issue ?  People interested can take this up.

**Comment by edengreen** [comment]
Added a PR for the change - #299

**Pull request merged**
