### PR TITLE
Adding support to $graphlookup

### PR DESCRIPTION
**Pull request by ymoran00**
Supporting the $grapLookup aggregation operation.
https://docs.mongodb.com/manual/reference/operator/aggregation/graphLookup/

### CODE REVIEW

**Comment by pcorpet** [comment]
Please cleanup your git history: it's hard to review the change proposed here. For instance you can squash all the commits related to your other PR in one commit, and then add the new stuff on top of it. Also try to use rebase instead of merge as it's easier to diff.

**Comment by ymoran00** [comment]
> Please cleanup your git history: it's hard to review the change proposed here. For instance you can squash all the commits related to your other PR in one commit, and then add the new stuff on top of it. Also try to use rebase instead of merge as it's easier to diff.

I'm a bit of a rookie in that matter. Can you elaborate what I need to do, or point me to a link explaining it more?
Thanks!

**Comment by ymoran00** [comment]
I've tried the scenario discussed here:
https://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed
To squash all $graphlookup commits to one commit.
Does that help?

**Comment by pcorpet** [comment]
Here's a short explanation: https://hackernoon.com/dont-fear-the-rebase-bca683888dae

Ideally, I would like to see on this branch only stuff that is on the main "develop" branch (i.e. not yours), and stuff that is part of this change (graphlookup). If you need to build on top of some other work of yours then I prefer to have this work only in one commit:

- branch origin/develop - commit 1 containing all previous work - commit 2 for graphlookup - commit 3 for graphlookup - .. etc

That way I can filter easily in GitHub review the commits for the graphlookup.

But now that I squashed your PR about string operations, you can rebase on origin/develop and there will only be your graphlookup work remaining on top.

**Comment by ymoran00** [comment]
I'm trying to fix a mess with a new PR - https://github.com/mongomock/mongomock/pull/523
Please see if it looks fine.
Thanks

**Pull request closed without merging**
