### PR TITLE
Implement the $expr operator.

### LINKED ISSUE #535: Feature Request: top level operator `$expr`
I have an aggregate query that includes this `$match` action in the pipeline:

```
{'$match': {'$or': [{'$expr': {'$gt': ["$latest", "$thing.analysisMeta.timestamp"]}},
                            {'thing.analysisMeta': None}]}},
```

In the real mongo database, this aggregate query works. With MongoMock >= 3.15.0, I get the error:

```
pymongo.errors.OperationFailure: unknown top level operator: $expr
```

In MongoMock 3.12.0 and 3.14.0, I do not get the error. I think it might be related to the fix for this issue: https://github.com/mongomock/mongomock/issues/495

For now, I can stay on 3.14.0, but would be nice to fix this in future releases so that we are not stuck.

### PR DESCRIPTION
**Pull request by pcorpet**
Fixes #535.

### CODE REVIEW

**Comment by 3ddi** [comment]
Great PR :) Is there a specific reason why is it stale?

**Comment by pcorpet** [comment]
I've discovered that `find({'$expr'` raises error in pymongo which is all silence in mongomock for now.

**Comment by reahaas** [comment]
What about this PR?
Will it merge in?

**Comment by pcorpet** [comment]
Sorry, I had left it out, resuming.

**Comment by reahaas** [comment]
Hooray!
I waited for this one, Thanks!

**Pull request merged**
