### PR TITLE
Removed object deletes from the drop_database call

### PR DESCRIPTION
**Pull request by ericchapman**

### CODE REVIEW

**Comment by codermpl** [comment]
Is this pull request going to be reviewed?

**Comment by ericchapman** [comment]
Note that I did not update the tests (I couldn't get them running) so someone will need to update the unit tests for this change

**Comment by srinivasreddy** [comment]
closing this PR for inactivity. Please feel free to comment to reopen.

**Comment by ZzAntares** [comment]
I can confirm this fixes the issue #238 why wasn't merged?

**Comment by srinivasreddy** [comment]
Would you like to take this up?  Could you please write unit test cases so that i can merge?

**Pull request closed without merging**
