### PR TITLE
Fixes #364. Support no-argument get_database() semantics

### LINKED ISSUE #364: Support get_database() with no name parameter
As of pymongo 3.5, `get_default_database()` [has been deprecated](http://api.mongodb.com/python/current/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient.get_default_database), and the recommended practice is to use `get_database()` [with no name parameter](http://api.mongodb.com/python/current/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient.get_database). Downstreams using this new method are currently unable to use the latest version of mongomock.

### PR DESCRIPTION
**Pull request by zachmullen**
@vmalloc this allows our downstream project https://github.com/girder/girder to use mongomock in our testing again. If you need someone to help maintain this project, I'm happy to review and merge important PRs and publish pypi packages if you are willing to grant access.

### CODE REVIEW

**Comment by zachmullen** [comment]
I also noticed this test failure locally, but I don't think it's a result of this change, since I'm also seeing it on the develop branch.

**Comment by danlamanna** [comment]
@vmalloc Thanks for going through the backlog! Mind taking a look at this one?

**Comment by vmalloc** [comment]
@danlamanna can you please share a link to a doc saying this is allowed in real pymongo?

**Comment by zachmullen** [comment]
Hi, I posted those links in the referenced issue #364.

Thanks!

**Comment by vmalloc** [comment]
@zachmullen oh I see. Thanks!

**Comment by vmalloc** [comment]
Sure, np. Thanks for contributing!

**Pull request merged**
