### PR TITLE
Adding arguments to `Collection.find` function

### PR DESCRIPTION
**Pull request by david1asher**
Adding missing arguments to `Collection.find` function that are present in [original pymongo implementation](http://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.find)
And changing test accordingly

### CODE REVIEW

**Comment by vmalloc** [comment]
Can you rebase on top of `develop` please?

**Comment by david1asher** [comment]
> Can you rebase on top of develop please?
@vmalloc shure

**Comment by vmalloc** [comment]
@david1asher the Travis build is failing. As we fixed all the failures on the develop branch, this implies the change introduces the failures. Can you please look into those?

**Comment by david1asher** [comment]
@vmalloc After rebasing on top of 401e4d60dcde92ed49c5eadfb757db602656ba37
CI test passed

**Pull request closed without merging**
