### PR TITLE
Implement the $addFields (alias $set) stage of aggregate.

### PR DESCRIPTION
**Pull request by pcorpet**
Implements #572

---
This change is [Reviewable](https://reviewable.io/reviews/mongomock/mongomock/574)

### CODE REVIEW

**Comment by pcorpet** [comment]
Also implements #555

**Comment by shapiy** [comment]
@pcorpet thanks for your great work first. Do you have an idea when this feature will be released?

**Comment by pcorpet** [comment]
@shapiy I'm waiting for a review. I'm an owner of this project but I prefer to have somebody else reviewing my code when I'm adding new features like this. Please take the time to review the changes and add comments if something is wrong or unclear.

**Comment by shapiy** [comment]
@pcorpet I am not very familiar with the code base. 

- I see that the code is sustained in one style, is clean and without obvious mistakes.
- I've installed mongomock from the feature branch and enabled my not-yet-passing unit test, and it works as expected.

If anyone is interested in testing:
`pip install git+https://github.com/pcorpet/mongomock.git@set-pipeline`

FYI,
While trying to post this comment with Reviewable, got this error: 
> Failed to publish: GitHub error 404 on POST https://api.github.com/repos/mongomock/mongomock/pulls/574/reviews: Not Found (The mongomock organization may need to authorize Reviewable as an accepted third party application.)

**Comment by pcorpet** [comment]
Thanks for your review. I'll go with that for now.

**Pull request merged**
