### PR TITLE
added collation as an attribute to the Cursor object

### PR DESCRIPTION
**Pull request by CalgaryMichael**
Relevant issue: #378

### CODE REVIEW

**Comment by vmalloc** [comment]
@CalgaryMichael  the build is failing...

**Comment by CalgaryMichael** [comment]
Looks like the build is passing

**Comment by vmalloc** [comment]
I don't see any functional difference being implemented here with or without collation... Am I missing something? Please see the note regarding stubs here: https://github.com/mongomock/mongomock/#important-note-about-project-status--development

**Comment by CalgaryMichael** [comment]
This commit does not intend to add any functionality. My intention was to merely fix an incompatibility issue with pyMODM. I did not add the functionality of Collation as I was unsure if that was a direction that was desired.

Essentially what I am doing here is the same thing that was done in [this commit](https://github.com/mongomock/mongomock/commit/447bc8710a6f57f23517ebd53c68004763177055).

**Comment by vmalloc** [comment]
Ok, but I'm still not super happy with this. The commit you mentioned was merged when I was less available as a maintainer, and it still goes a bit against what Mongomock tries to achieve. However I will merge this as it sounds like there shouldn't be much harm from this particular case. Thanks for contributing!

**Pull request merged**
