### PR TITLE
Make distinct() work with arrays of dicts

### LINKED ISSUE #750: distinct fails for array field with dicts
A TypeError is raised when `distinct` is performed on an array field with dict values. 

In mongodb:
```python
>>> coll.insert_many([{'foo': [{'a': 1}, {'b': 2}]}, {'foo': [{'b': 2}, {'c': 3}]}])
<pymongo.results.InsertManyResult object at 0xffffaa80be40>
>>> coll.distinct('foo')
[{'a': 1}, {'b': 2}, {'c': 3}]
```

In mongomock:
```python
>>> coll.insert_many([{'foo': [{'a': 1}, {'b': 2}]}, {'foo': [{'b': 2}, {'c': 3}]}])
<pymongo.results.InsertManyResult object at 0xffffbc2d8100>
>>> coll.distinct('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python-pp/lib/python3.8/site-packages/mongomock/collection.py", line 1708, in distinct
    return self.find(filter).distinct(key)
  File "/opt/python-pp/lib/python3.8/site-packages/mongomock/collection.py", line 1952, in distinct
    unique.update(
TypeError: unhashable type: 'dict'
```

### PR DESCRIPTION
**Pull request by niklasj**
Fixes #750.

### CODE REVIEW

**Comment by pcorpet** [comment]
Very nice fix. Thanks.

**Comment by pcorpet** [comment]
I'm not ure why the CI didn't run. Can you try to rebase and push again please?

**Comment by niklasj** [comment]
Sure thing!

**Comment by pcorpet** [comment]
Perfect, let's merge!

**Pull request merged**
