### PR TITLE
Forward codec options (#793 continuation)

### PR DESCRIPTION
**Pull request by ramnes**
Salut Pascal. :)

I'm trying to use mongomock as a test backend (through [Mongo-Thingy](https://github.com/Refty/mongo-thingy) and [mongomock-motor](https://github.com/michaelkryukov/mongomock_motor)), but the lack of UUID support makes it impossible.

So here is a continuation PR of #793, so that #745 can get closed; it seems like there are quite a few other persons interested in UUID support at this point (cc @Kalbi @elanou @joshuashaffer @jschlyter @Greeengooo @arturmkr @hugo-azevedo).

Looking at your GitHub activity, I seem to understand that you're busy with other things than mongomock at the moment, so I'll do my best to answer ASAP to any kind of feedback.

Thanks for the great library!

### CODE REVIEW

**Comment by lewis-kori** [comment]
@ramnes were you able to proceed without the patches?
We're also experiencing the same issues.

**Comment by ramnes** [comment]
I don't understand your question. Most of my test suite passes with these patches applied; a few don't but that's not related to UUID support.

**Comment by lewis-kori** [comment]
@ramnes  Whenever I run my test suite, they fail because the codecs aren't forwarded to the BSON encoder and the [UUID validation check here](https://github.com/mongodb/mongo-python-driver/blob/master/bson/binary.py#L266-L274) fails.
So I was wondering how you were able to bypass these two issues.
I'm using mongomock v4.1.2

with mongoengine which has a dependency on pymongo v4.3.3.

**Comment by ramnes** [comment]
By using this patch?

**Comment by ramnes** [comment]
I'm closing this PR since I've lost interest in this. I'll leave the branch in my repository, feel free to rebase any future PR on it if you're willing to take up the torch. :)

**Comment by lewis-kori** [comment]
thanks, @ramnes 
I haven't used the patch yet. seems like you have.
are you able to install it directly with pip or GitHub in a CI/CD pipeline?
we do need this working in such a workflow, but we aren't strict on deadlines.

**Comment by ramnes** [comment]
https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/

**Comment by lewis-kori** [comment]
thank you!

**Pull request closed without merging**
