### PR TITLE
Fix skipping of MongoClientAggregateTest

### PR DESCRIPTION
**Pull request by matt-snider**
As discussed in #237, tests that require both pymongo and pyexecjs aren't being run at all since there is no tox factor which includes both. To fix this, I've just added the pyexecjs dependency to the pymongo dependencies. I'll add the commit that fixes the failing tests after the CI runs

### CODE REVIEW

**Comment by matt-snider** [comment]
Hmm okay, well it looks like this change uncovered some failing tests that weren't being run. They seem to only be failing because the CI runs with an older version of mongo (2.6.12). 

All tests pass when running it locally with mongo 3.2

**Comment by matt-snider** [comment]
Hi @srinivasreddy! Any comment or feedback on tis?

**Comment by srinivasreddy** [comment]
@matt-snider  Thanks for the PR and apologies for the late reply.

Could you please resolve conflicts. I will take a look in a day or two.
 
Thanks for your patience.

**Comment by matt-snider** [comment]
@srinivasreddy No problem. I've rebased onto develop and reverted one commit, as it was fixed in 50c694180a9d266d4a5bb3e322bb57bbf6ee8783

**Comment by matt-snider** [comment]
But I guess the Travis build won't be triggered by an old commit. Can it be triggered manually?

**Comment by srinivasreddy** [comment]
@matt-snider  Yes. You can do that by closing the pr and opening again. :smile:

**Comment by matt-snider** [comment]
As mentioned above, the failing tests are due to the mongo version used. The $min operator for $project stages [only became available in v3.2](https://docs.mongodb.com/v3.2/reference/operator/aggregation/min/). 

I've updated the `tox.ini` file to use mongodb 3.2, but I'm not sure if this is desirable. 

Let me know what you think.

**Comment by srinivasreddy** [comment]
I am not sure of this.  tagging. @mdomke  @vmalloc

**Comment by pcorpet** [comment]
This was eventually fixed by #424

**Pull request closed without merging**
